### ISSUE TITLE
More options for email adresses requested

### ISSUE THREAD

**Issue by brandsis** [youngcut/kirby-form-block-suite#48]
Last night I updated my Form Block Suite plugin to the latest 4.1.1 version and the 'from_email' config setting appears not to be working now. It was working perfectly before.

This is what I have in my `config.php` file...

```
'microman.formblock' => [
    'from_email' => ["form@brandsistency.com" => "Brandsistency website"]
],
```

But this is how my Inbox now looks...

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/ccee6396-ea97-4476-8f43-607f60c26108)

All I did was replace the plugin folder. I made no changes to `config.php` or to the form in the Panel. Did I miss a required change?

**Comment by youngcut** [comment]
Is could reproduce the Bug and it's fixed in [Version 4.1.2](https://github.com/youngcut/kirby-form-block-suite/releases/tag/v4.1.2).
If it still occurs, make sure the field **Recipient's address** is empty.

**Comment by brandsis** [comment]
Hi, Roman. I've installed 4.1.2, cleared both the Kirby and browser cache and retested the form. The issue is still occurring. The submission process works fine but the received email still displays the raw server email address as the sender, rather than what's configured in `config.php`.

I'm not sure I understand your suggestion to empty the **Recipient's address** field. I did try it but that means, of course, that the email does not send and it's the email that's the issue.

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/2f405faa-327e-4a4c-9af8-412010e9633f)

**Comment by brandsis** [comment]
Note that this test was done in my [test site](https://brandsistency.dev/brandsistency/contact), which is internet-facing.

**Comment by youngcut** [comment]
Sorry, something was missing try again with version 4.1.4.

**Comment by brandsis** [comment]
Roman, I've installed v4.1.3 and still no joy...

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/ca6212e7-1558-4fc7-a465-d290877e96b2)

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/f4fc9eab-36d2-480e-a782-2736a913b87b)

**Comment by brandsis** [comment]
Hi, Roman.

For the purposes of retesting, I reverted my plugin to v4.1.0, which was the version running when the `from_email` setting was last working, and it has not fixed the issue. I'm not sure why. As before, I have this in my config...

```
'microman.formblock' => [
    'from_email' => ["form@brandsistency.com" => "Brandsistency website"]
],
```

...but emails are still arriving from 'brandsis@premium88.web-hosting.com'.

(As this hasn't worked, I'll update back to v4.1.3.)

**Comment by youngcut** [comment]
It's fixed in 4.2.1. Please close this Issue if it's solved....

**Comment by brandsis** [comment]
Hi, Roman. It looks like the display name/email address is **not** picking from the `from_email` config setting but is instead using the 'Recipient's address' field from the Panel. In other words, the email says it's coming from the same email address that it's being sent to.  I have `'from_email' => ["form@brandsistency.com" => "Brandsistency website"]` in `config.php` but this is how the email arrives...

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/22ff0952-0a33-49d9-b2bb-3ab470a6b9b6)

Similar to the submit button text discussed separately, it would be helpful to be able to specify different senders – at least different display names – for different forms. For example, "Website contact form" or "Website application form". Would that be possible using _Extend options_ as well? Or, would it be worth adding new fields "Sender's address" and "Sender's display name" in the Send notification section?

**Comment by brandsis** [comment]
Thanks for v4.3.0, Roman. I do like your treatment where `notify_from` is the `{{ name }} <{{ email }}>` of the submitter. And the reply address is the submitter's as well.

Are those new settings included by default or do I need to add them as fields via `form_notify.yml` and populate them in the Panel? I installed 4.3.0 and then deleted `from_email` from `config.php` – thinking the new items would handle this – and now I am not receiving emails at the `notify_email` address.

**Comment by brandsis** [comment]
Also, is there a way to hide/remove the CAPTCHA response from the email? It occurs to me that the recipient of the submission doesn't need to see the response to that question, as its only purpose is spam protection.

I have managed to hide it from the `k-dialog` modal view in the Panel through `panel.css` but not sure if/how I can do the same for the email output.

**Comment by brandsis** [comment]
Hi, Roman @youngcut.

I don't know why it wasn't working before but submission emails have now started to arrive, which is great news. I can now get this working for the client site I'm migrating to Kirby. 😀

Whilst they're not crucial, it would be helpful if you can feed back on the other items, as I think they would improve the UX...
* Fields added to (a copy of) `form_notify.yml` to be grouped within that section in the Panel. Currently, they appear at the bottom of the options drawer. So, for example, the `notify_from` and `notify_reply` fields are separated from `notify_email`, `notify_subject` and `notify_body`.
* The same for `form_confirm.yml` fields.
* The spam protection entry to be hidden or hideable from the response in the Panel (which I've done via `panel.css`) and from the notification and confirmation emails.

Many thanks.

**Comment by brandsis** [comment]
Hi, Roman. I realised that I was slightly wrong in my last comment. Unless I am doing something wrong, which is perfectly possible, my custom `form_notify.yml` is not working.

The reason the `notify_from` and `notify_reply` fields were at the bottom of the options drawer is that I'd mistakenly left them in the `form_options.yml` file. But if I remove them there, so they are included ONLY in `/site/blueprints/snippets/form_notify.yml`, they do NOT appear in the Panel even after clearing all cache. They only appear in the Panel if they are included in `form_options.yml`.

This is my `form_notify.yml` content...

```
enable_notify:
  type: toggle
  label: form.block.options.enable_notify

notify_email:
  label: form.block.options.notify_email
  type: text
  placeholder: form.block.options.notify_placeholder
  help: form.block.options.email.help
  width: 1/2
  when:
    enable_notify: true

notify_subject:
  label: form.block.options.notify_subject
  type: text
  help: form.block.default.help
  width: 1/2
  when: 
    enable_notify: true
    
notify_body:
  label: form.block.options.notify_body
  type: textarea
  help: form.block.default.help
  buttons: false
  when:
    enable_notify: true

notify_from:
  label: Sender's address
  type: text
  width: 1/2
  when:
    enable_notify: true

notify_reply:
  label: Reply address
  type: text
  width: 1/2
  when:
    enable_notify: true

line1:
  type: line
  when:
    enable_notify: true
```

But those fields do not appear in the Panel...

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/5231e8f7-7064-4c73-8436-b6dcf52e47ad)

I noticed that the README has the fields as `type: email` but I had them as text fields when in `form_options.yml` and it was working. I shall put the fields back into `form_options.yml`, at least for now, so that the emails work again.
