### ISSUE TITLE
Question: can I set different submit button text for different forms

### ISSUE THREAD

**Issue by brandsis** [youngcut/kirby-form-block-suite#51]
I'm in the process of migrating a charity client's website (from MODX) to Kirby. There are two pages with forms – a simple [contact form](https://wendovertrust.org/contact) and an [application form](https://wendovertrust.org/apply) for funding grants – that I need to replicate using Form Block Suite.

However, as the submit button text is controlled through translations in `config.php`, is there a way that I can specify different button text for the different forms? For example, "Send message" and "Submit application".

This is my current config entry...

```
	'microman.formblock' => [
		'from_email' => ["form@brandsistency.com" => "Brandsistency website"],
		'translations' => [
			'en' => [
				'send_button' => 'Send message',
				'loading' => 'Send message'
			]
		]
	],
```

**Comment by youngcut** [comment]
Yes you can: https://github.com/youngcut/kirby-form-block-suite?tab=readme-ov-file#messages

**Comment by brandsis** [comment]
Thanks, Roman. I thought I might have missed it in the docs. I'll give it a try.

If I create custom fields for `send_button` and `loading`, will they automatically get picked up by the front-end snippets/templates based on field name? (The instructions only refer to blueprints.)

**Comment by youngcut** [comment]
It is a blueprint. You will have a field in the options tab, where you can enter the text.

site/blueprints/snippets/form_options.yml
```yml
send_button:
  label: My custom button text
  type: text
```

<img width="627" alt="Bildschirmfoto 2024-04-30 um 11 33 35" src="https://github.com/youngcut/kirby-form-block-suite/assets/4754476/e8cd2329-f055-470e-a74e-368a1d6ac097">

**Comment by brandsis** [comment]
Thanks, Roman. I've done that successfully.

**Comment by addedlovely** [comment]
Does this still work, I can't see any custom fields. 
I have the following in the `site/blueprints/snippets` folder, as 'form_options.yml'.

```
redirect:
  type: toggle
  label: form.block.options.redirect
  width: 1/3
  text:
    - form.block.options.redirect.on
    - form.block.options.redirect.off

success_message:
  label: form.block.options.success_text
  type: writer
  help: form.block.default.help
  width: 2/3
  when:
    redirect: false

success_url:
  label: form.block.options.success_url
  type: pages
  min: 1
  width: 2/3
  when:
    redirect: true
    
send_button:
  label: Submit button text
  type: text
```
